/* Autogenerated file : do not edit manually ! */
        
#ifndef VARDESC_H
#define VARDESC_H
#include <stdint.h>
#include "trace_writer.h"

/* EEPROM description table */
#define EEPROM_QTY 38
desc_t eeprom_desc[] = { 
	{"wheelImpulse", 8, "#", 0, "U08", 0, 0},
	{"timerLed", 16, "$", 1, "U16", 0, 0},
	{"wheelSize", 8, "%", 3, "U08", 0, 0},
	{"PMHOffset", 8, "&", 4, "U08", 0, 0},
	{"maxRPM", 16, "'", 5, "U16", 0, 0},
	{"maxTemp", 8, "(", 7, "U08", 0, 0},
	{"minBat", 8, ")", 8, "U08", 0, 0},
	{"tpsMin", 8, "*", 9, "U08", 0, 0},
	{"tpsMax", 8, "+", 10, "U08", 0, 0},
	{"map0", 8, ",", 11, "U08", 0, 0},
	{"map5", 8, "-", 12, "U08", 0, 0},
	{"battRatio", 8, ".", 13, "U08", 0, 0},
	{"ignDuration", 16, "/", 14, "U16", 0, 0},
	{"ignOverheat", 8, "0", 16, "U08", 0, 0},
	{"ignStarter", 8, "1", 17, "U08", 0, 0},
	{"injectorOpen", 16, "2", 18, "U16", 0, 0},
	{"injectorStart", 16, "3", 20, "U16", 0, 0},
	{"holdPWM", 8, "4", 22, "U08", 0, 0},
	{"injectorRate", 16, "5", 23, "U16", 0, 0},
	{"injAdv", 8, "6", 25, "U08", 0, 0},
	{"targetAfr", 8, "7", 26, "U08", 0, 0},
	{"injStarter", 16, "8", 27, "U16", 0, 0},
	{"injAfterStartDur", 16, "9", 29, "U16", 0, 0},
	{"injOverheat", 8, ":", 31, "U08", 0, 0},
	{"injTestPW", 16, ";", 32, "U16", 0, 0},
	{"injTestCycles", 16, "<", 34, "U16", 0, 0},
	{"rpmBins", -1, "=", 36, "array", 0, 0},
	{"loadBins", -1, ">", 56, "array", 0, 0},
	{"injTable", -1, "?", 66, "array", 0, 0},
	{"ignTable", -1, "@", 166, "array", 0, 0},
	{"iatCal", -1, "A", 266, "array", 0, 0},
	{"cltCal", -1, "B", 286, "array", 0, 0},
	{"injAfterStartTbl", -1, "C", 306, "array", 0, 0},
	{"injWarmupTbl", -1, "D", 326, "array", 0, 0},
	{"lapLength", 16, "E", 346, "U16", 0, 0},
	{"user1", 16, "F", 348, "U16", 0, 0},
	{"user2", 16, "G", 350, "U16", 0, 0},
	{"user3", 16, "H", 352, "U16", 0, 0},
};
        
/* output channel/ current data description table */
#define CURDATA_QTY 33
desc_t curData_desc[] = { 
	{"rawBattery", 8, "I", 0, "U08", 0, 0},
	{"rawClt", 8, "J", 1, "U08", 0, 0},
	{"rawIat", 8, "K", 2, "U08", 0, 0},
	{"rawTps", 8, "L", 3, "U08", 0, 0},
	{"rawMap", 8, "M", 4, "U08", 0, 0},
	{"battery", 8, "N", 5, "U08", 0, 0},
	{"CLT", 8, "O", 6, "U08", 0, 0},
	{"IAT", 8, "P", 7, "U08", 0, 0},
	{"TPS", 8, "Q", 8, "U08", 0, 0},
	{"MAP", 8, "R", 9, "U08", 0, 0},
	{"TPSVariation", 8, "S", 10, "S08", 0, 0},
	{"rpm", 16, "T", 11, "U16", 0, 0},
	{"load", 8, "U", 13, "U08", 0, 0},
	{"speed", 16, "V", 14, "U16", 0, 0},
	{"engineState", 8, "W", 16, "U08", 0, 0},
	{"TPSState", 8, "X", 17, "U08", 0, 0},
	{"injK", 16, "Y", 18, "U16", 0, 0},
	{"injQFuel", 16, "Z", 20, "U16", 0, 0},
	{"injPulseWidth", 16, "[", 22, "U16", 0, 0},
	{"injStart", 16, "\\", 24, "U16", 0, 0},
	{"injOffset", 16, "]", 26, "S16", 0, 0},
	{"injStartOffset", 8, "^", 28, "S08", 0, 0},
	{"injAfterStartEnrich", 8, "_", 29, "U08", 0, 0},
	{"injWarmupEnrich", 8, "`", 30, "U08", 0, 0},
	{"injVE", 8, "a", 31, "U08", 0, 0},
	{"advance", 8, "b", 32, "U08", 0, 0},
	{"ignOffset", 8, "c", 33, "S08", 0, 0},
	{"second", 16, "d", 34, "U16", 0, 0},
	{"injTestMode", 8, "e", 36, "U08", 0, 0},
	{"injTestCycles", 16, "f", 37, "U16", 0, 0},
	{"debug1", 16, "g", 39, "U16", 0, 0},
	{"debug2", 16, "h", 41, "U16", 0, 0},
	{"debug3", 16, "i", 43, "U16", 0, 0},
};
        
#endif
